### PR TITLE
added hr styling to post page

### PR DESCRIPTION
**Pull request by rodolfo42**
Hello Shashank

Loving your theme, I've shown it to a few friends of mine and they went nuts!

Just another small change I've made to my copy of the theme and I think it would be useful for everyone else.

The `hr` is unstyled, noticed when using it via markdown (`---` on a blank line) and I've decided to fix by applying the same colors as the top/bottom borders of `article` and `div.share`, for example, to preserve the look 'n' feel.

Here's how it was before the fix:

Before:
image

After:
image

Hope you like it

Thanks again!

### CODE REVIEW

**Comment by shashankmehta** [comment]
There are probably a lot of small little things than can be made better, like this `hr`. Thanks for the pull request!

**Comment by alexrussell** [comment]
[This commit ](https://github.com/shashankmehta/greyshade/commit/98c94a562d367bb9ccf9e4c941dc1c23ba8c0134) appears to have been undone at one point (but it's hard for me to search to repo to find out when). Any reason or was it an accident? I happened to notice today that my hrs weren't being styled and came to submit an issue (but thought I'd search first) and found this issue.

**Comment by alexrussell** [comment]
Ahh, turns out searching with git log is easier than I thought. Here's the commit that undid the work: https://github.com/shashankmehta/greyshade/commit/e7049b9d8dbc076840180a336334d90dbe611794

**Comment by shashankmehta** [comment]
Hmm, I'm not sure if this removal was on purpose or accidental. The commit that undid this was for code blocks. Maybe `hr` was creating problems there. I'll take a look and push a fix. Thanks for pointing it out!

**Comment by alexrussell** [comment]
No problem, and thanks for looking into it. Kinda looks like it may have been by accident but as you say, it's hard to tell.

**Pull request merged**
