### PR TITLE
Coderwall link

### PR DESCRIPTION
**Pull request by barisbalic**
Added image and style for coderwall, should the user decide to set a 'coderwall_user' in _config.yml

### CODE REVIEW

**Comment by rodolfo42** [comment]
Didn't know about coderwall, just registered. Would be nice to display the badges, just bellow your bio paragraph.

**Comment by barisbalic** [comment]
Yup, I was thinking of adding something like that but then thought that Greyshade is a very minimal, clean, theme.  After that I took a look and found that there are some coderwall plugins already.

**Comment by shashankmehta** [comment]
Thanks @barisbalic! Yeah badges on a blog would be too much for Greyshade.

**Comment by rodolfo42** [comment]
You're right, it would quickly clutter the clean look. I'm already using the coderwall link, thanks!

**Comment by barisbalic** [comment]
Only just noticed these messages!  No problem guys, thanks for building such a nice theme.

**Pull request merged**
