### PR TITLE
adding email badge and icon

### PR DESCRIPTION
**Pull request by miguelgraz**
Using the `email` field that already exists in `_config.yml`.

### CODE REVIEW

**Comment by gabrielluong** [comment]
Instead of a gmail specific badge, wouldn't it be better to have a general email badge?

**Comment by miguelgraz** [comment]
It is a good point, yeah. 

I believe we can have both, if this sounds good I'll change the PR to add this general email badge.

**Comment by shashankmehta** [comment]
Yeah it would be better to have a general email badge although gmail is more or less synonymous with email anyways.

**Comment by miguelgraz** [comment]
Still if you guys don't have anything against I'd have both, or is it mandatory to delete the gmail badge?

**Comment by gabrielluong** [comment]
I think we can keep the gmail badge, but allow for any email to be specified.

**Comment by miguelgraz** [comment]
Deal, will do it ASAP =)

On Mon, Oct 7, 2013 at 2:54 PM, Gabriel Luong notifications@github.comwrote:

> I think we can keep the gmail badge, but allow for any email to be
> specified.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shashankmehta/greyshade/pull/51#issuecomment-25829986
> .

## 

Miguel Grazziotin
Miguelgraz.com

**Comment by gabrielluong** [comment]
I am also curious if you can find a badge that is similar in style with the other badges (ie, transparent).

**Comment by miguelgraz** [comment]
I was considering the use of this icon from octopress default theme
https://github.com/imathis/octopress/blob/master/.themes/classic/source/images/email.png

Is it good enough?

On Mon, Oct 7, 2013 at 4:19 PM, Gabriel Luong notifications@github.comwrote:

> I am also curious if you can find a badge that is similar in style with
> the other badges (ie, transparent).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shashankmehta/greyshade/pull/51#issuecomment-25836976
> .

## 

Miguel Grazziotin
Miguelgraz.com

**Comment by shashankmehta** [comment]
I'm not sure if the logo used matches the design being already used. 
I think we can use the GMail icon from this [icon-set](http://simpleicons.org/). In the repo, there's white version too, the kind that's being used already

**Comment by shashankmehta** [comment]
Also, instead of having two different icons, I think we should keep just one. No matter what email providers is being used by the user, we'll show the gmail icon only.

`_config.yml` already has the email field. If it is filled then rss feed of the blog includes the email address. This means that the user wants to display his email to his readers. So if this field is set, let's show the email id too.
Views on this?

**Comment by miguelgraz** [comment]
Not sure about using the email field that we already have in `_config.yml`, if you guys believe we won't have a user that wants to display his email in the RSS feed and doesn't want to display the email in the site, then it is a good approach.
Let's stick to this rule, then?

**Comment by miguelgraz** [comment]
I wasn't sure about the color either, tried to use a dark one, would love an opinion in this.

**Comment by shashankmehta** [comment]
Yeah this looks fine. Can you squash your commits to one? I'll merge after that. Thanks!

**Comment by miguelgraz** [comment]
I finally made it, sorry for the delay =)

**Comment by shashankmehta** [comment]
Thanks!

**Comment by miguelgraz** [comment]
Thank you! =)

**Pull request merged**
